import type { AccessFeatureKind, AccessStatus, PoiCategory } from '../domain/types';

/** Every user-facing string lives here so the UI can be translated later. */
export const strings = {
  appName: 'Mapa USP Butantã',
  close: 'Fechar',
  loading: 'Carregando…',
  dataError: 'Não foi possível carregar os dados do campus.',
  map: {
    ariaLabel: 'Mapa do campus Butantã da USP',
    loading: 'Carregando mapa…',
    error: 'Não foi possível carregar o mapa. Verifique sua conexão.',
  },
  search: {
    placeholder: 'Buscar prédio, instituto ou local',
    label: 'Buscar no campus',
    clear: 'Limpar busca',
    results: 'Resultados da busca',
    noLocalResults: 'Nenhum resultado no campus',
    offCampus: 'Fora do campus',
    institute: 'Unidade',
  },
  indoor: {
    open: 'Ver planta interna',
    close: 'Fechar planta interna',
    levels: 'Andares',
    level: (level: string) => `Nível ${level}`,
    error: 'Não foi possível carregar a planta interna.',
    categories: {
      classroom: 'Sala de aula',
      studio: 'Estúdio',
      laboratory: 'Laboratório',
      library: 'Biblioteca',
      museum: 'Museu',
      auditorium: 'Auditório',
      administration: 'Administração',
      department: 'Departamento',
      food: 'Alimentação',
      services: 'Serviços',
      bathroom: 'Sanitário',
      hall: 'Salão',
      circulation: 'Circulação',
      ramp: 'Rampa',
      stairs: 'Escada',
      elevator: 'Elevador',
      void: 'Vazio',
      technical: 'Área técnica',
    },
  },
  building: {
    unnamed: 'Edifício sem nome',
    kinds: {
      university: 'Prédio universitário',
      dormitory: 'Moradia estudantil',
      roof: 'Cobertura',
      retail: 'Comércio',
      commercial: 'Comércio',
      construction: 'Em construção',
      school: 'Escola',
      greenhouse: 'Estufa',
      hospital: 'Hospital',
      yes: 'Edifício',
    } as Record<string, string>,
  },
  wiki: {
    about: (name: string) => `${name} na Wikipédia`,
    readMore: 'Ler na Wikipédia',
    license: 'Wikipédia, CC BY-SA',
    photos: (title: string) => `Fotos: ${title}`,
    photoAlt: (title: string, position: number) => `${title}, foto ${position}`,
    photoBy: (author: string | undefined) => (author ? `Foto: ${author}` : 'Foto'),
    commons: 'Wikimedia Commons',
    website: 'Site',
  },
  carousel: {
    previous: 'Foto anterior',
    next: 'Próxima foto',
    position: (current: number, total: number) => `${current}/${total}`,
  },
  institute: {
    buildings: 'Prédios',
    noNamedBuildings: 'Nenhum prédio com nome cadastrado.',
  },
  poi: {
    inside: 'Em',
    openingHours: 'Horário',
    categories: {
      food: 'Alimentação',
      library: 'Biblioteca',
      bank: 'Banco',
      atm: 'Caixa eletrônico',
      water: 'Bebedouro',
      toilets: 'Banheiro',
      bike_rental: 'Estação de bicicletas',
      bike_parking: 'Bicicletário',
      parking: 'Estacionamento',
      health: 'Saúde',
      culture: 'Cultura',
      sport: 'Esporte',
      park: 'Área verde',
      shop: 'Loja',
      info: 'Informações',
      other: 'Local',
    } satisfies Record<PoiCategory, string>,
  },
  transit: {
    stop: 'Ponto de ônibus',
    arrivals: 'Próximos ônibus',
    lines: 'Linhas',
    live: 'Previsão ao vivo',
    scheduledNoBuses: 'Horário programado · sem ônibus previstos agora',
    scheduledNoLive: 'Horário programado · dados ao vivo indisponíveis',
    none: 'Sem ônibus previstos agora.',
    noneNoLive: 'Dados ao vivo indisponíveis e sem horários programados para este ponto.',
    unavailable: 'Não foi possível obter as previsões agora.',
    now: 'agora',
    minutes: 'min',
    today: 'hoje',
    tomorrow: 'amanhã',
    accessibleBus: 'acessível',
    bus: 'Ônibus',
    busAccessible: 'Ônibus acessível para cadeira de rodas.',
    busNotAccessible: 'Ônibus sem acessibilidade para cadeira de rodas.',
    busPrefix: 'Prefixo',
    busSeen: (seconds: number) => (seconds < 90 ? `posição de ${seconds} s atrás` : `posição de ${Math.round(seconds / 60)} min atrás`),
    busGone: 'Este ônibus não está mais no mapa.',
    busOffline: 'Sem conexão. A posição do ônibus volta quando a internet voltar.',
    followArrival: (line: string) => `Acompanhar o ônibus ${line} no mapa`,
    allArrivals: 'Todas as chegadas',
    follow: 'Seguir veículo',
    following: 'Posição ao vivo · seguindo',
    followPaused: 'Posição ao vivo · acompanhamento pausado',
    lineStops: 'Pontos da linha',
    stopCount: (count: number) => (count === 1 ? '1 ponto' : `${count} pontos`),
    passed: 'Passou',
    showPassed: (count: number) => (count === 1 ? 'Mostrar 1 ponto anterior' : `Mostrar ${count} pontos anteriores`),
    hidePassed: 'Ocultar pontos anteriores',
    yourStop: 'Seu ponto',
    terminus: 'Ponto final',
    busHere: 'Ônibus aqui',
    estimate: (label: string) => `≈ ${label}`,
    estimatesNote: 'Horários com ≈ são estimativas pela distância; o do seu ponto é a previsão da SPTrans.',
    busesUnavailable: 'Ônibus ao vivo indisponíveis',
  },
  lite: {
    label: 'Visualização 3D',
    hint: 'Árvores e ônibus em 3D. Desative se o mapa ficar lento.',
    autoEnabled: 'Modo leve ativado para o mapa ficar mais fluido.',
    undo: 'Desfazer',
  },
  layers: {
    button: 'Camadas do mapa',
    title: 'Camadas',
    pois: 'Locais no mapa',
    otherPois: 'Outros',
    hiddenInAccessMode: 'Os locais ficam ocultos enquanto a visão de acessibilidade está ativa.',
  },
  offline: {
    banner: 'Sem conexão · ônibus ao vivo indisponíveis',
    arrivals: 'Sem conexão. As previsões voltam quando a internet voltar.',
  },
  update: {
    available: 'Há uma nova versão do mapa.',
    reload: 'Atualizar',
  },
  route: {
    open: 'Traçar rota',
    title: 'Rota a pé',
    toHere: 'Rota até aqui',
    from: 'De',
    to: 'Para',
    choose: 'Escolher…',
    swap: 'Inverter origem e destino',
    pickHint: { from: 'Toque no mapa ou use a busca para escolher a origem.', to: 'Toque no mapa ou use a busca para escolher o destino.' },
    myLocation: 'Minha localização',
    useMyLocation: 'Usar minha localização',
    locationError: 'Não foi possível obter sua localização.',
    mapPoint: 'Ponto no mapa',
    profile: 'Tipo de rota',
    profiles: { walk: 'A pé', wheelchair: 'Sem degraus' },
    calculating: 'Calculando rota…',
    error: 'Não foi possível calcular a rota agora.',
    offline: 'Sem conexão. Rotas precisam de internet.',
    stepFree: {
      guaranteed: 'Rota sem degraus.',
      'best-effort': 'Evita escadas quando possível, mas pode conter degraus.',
      no: '',
    },
    hasStairs: 'Atenção: esta rota passa por escadas.',
    quota: 'O serviço de rotas sem degraus atingiu o limite de uso; esta rota veio de outro serviço.',
    takeStairs: 'Suba ou desça a escada.',
    stairs: 'escada',
    steps: 'Passo a passo',
    providers: { valhalla: 'Rota: Valhalla (FOSSGIS)', ors: 'Rota: openrouteservice' },
    dataCredit: 'dados © OpenStreetMap',
  },
  place: {
    offCampus: 'Local fora do campus',
  },
  access: {
    title: 'Acessibilidade',
    status: {
      yes: 'Acessível',
      partial: 'Parcialmente acessível',
      no: 'Não acessível',
      unknown: 'Sem informação',
    } satisfies Record<AccessStatus, string>,
    unknownHint: 'Ninguém registrou ainda a acessibilidade deste local.',
    source: { osm: 'Fonte: OpenStreetMap', curated: 'Fonte: levantamento do projeto' },
    toggle: 'Acessibilidade',
    legend: 'Legenda de acessibilidade',
    show: 'Mostrar no mapa',
    kinds: {
      ramp: 'Rampa',
      elevator: 'Elevador',
      entrance: 'Entrada',
      toilet: 'Banheiro',
      parking: 'Estacionamento',
      kerb: 'Meio-fio',
      steps: 'Escada',
    } satisfies Record<AccessFeatureKind, string>,
    toilet: 'Banheiro acessível',
    elevator: 'Elevador',
    parking: 'Vagas reservadas',
    level: 'Andar',
    checked: 'Verificado em',
    features: 'Recursos neste prédio',
    yes: 'Sim',
    no: 'Não',
  },
} as const;

/** `2026-10-10` → `10/10/2026`, without going through a time zone. Other formats are shown as written. */
export function formatDate(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  return match ? `${match[3]}/${match[2]}/${match[1]}` : iso;
}

export const buildingKindLabel = (kind: string) => strings.building.kinds[kind] ?? strings.building.kinds.yes!;
