import type { AccessFeatureKind, AccessStatus, PoiCategory } from '../domain/types';

/** Every user-facing string lives here so the UI can be translated later. */
export const strings = {
  appName: 'Mapa USP Butantã',
  close: 'Fechar',
  loading: 'Carregando…',
  dataError: 'Não foi possível carregar os dados do campus.',
  map: {
    ariaLabel: 'Mapa do campus Butantã da USP',
    loading: 'Carregando mapa…',
    error: 'Não foi possível carregar o mapa. Verifique sua conexão.',
  },
  search: {
    placeholder: 'Buscar prédio, instituto ou local',
    label: 'Buscar no campus',
    results: 'Resultados da busca',
    noLocalResults: 'Nenhum resultado no campus',
    offCampus: 'Fora do campus',
    institute: 'Unidade',
  },
  building: {
    unnamed: 'Edifício sem nome',
    kinds: {
      university: 'Prédio universitário',
      dormitory: 'Moradia estudantil',
      roof: 'Cobertura',
      retail: 'Comércio',
      commercial: 'Comércio',
      construction: 'Em construção',
      school: 'Escola',
      greenhouse: 'Estufa',
      hospital: 'Hospital',
      yes: 'Edifício',
    } as Record<string, string>,
  },
  institute: {
    buildings: 'Prédios',
    noNamedBuildings: 'Nenhum prédio com nome cadastrado.',
  },
  poi: {
    inside: 'Em',
    openingHours: 'Horário',
    categories: {
      food: 'Alimentação',
      library: 'Biblioteca',
      bank: 'Banco',
      atm: 'Caixa eletrônico',
      water: 'Bebedouro',
      toilets: 'Banheiro',
      bike_rental: 'Estação de bicicletas',
      bike_parking: 'Bicicletário',
      parking: 'Estacionamento',
      health: 'Saúde',
      culture: 'Cultura',
      sport: 'Esporte',
      park: 'Área verde',
      shop: 'Loja',
      info: 'Informações',
      other: 'Local',
    } satisfies Record<PoiCategory, string>,
  },
  transit: {
    stop: 'Ponto de ônibus',
    arrivals: 'Próximos ônibus',
    lines: 'Linhas',
    live: 'Previsão ao vivo',
    scheduledNoBuses: 'Horário programado · sem ônibus previstos agora',
    scheduledNoLive: 'Horário programado · dados ao vivo indisponíveis',
    none: 'Sem ônibus previstos agora.',
    noneNoLive: 'Dados ao vivo indisponíveis e sem horários programados para este ponto.',
    unavailable: 'Não foi possível obter as previsões agora.',
    now: 'agora',
    minutes: 'min',
    today: 'hoje',
    tomorrow: 'amanhã',
    accessibleBus: 'acessível',
    bus: 'Ônibus',
    busAccessible: 'Ônibus acessível para cadeira de rodas.',
    busNotAccessible: 'Ônibus sem acessibilidade para cadeira de rodas.',
    busPrefix: 'Prefixo',
    busSeen: (seconds: number) => (seconds < 90 ? `posição de ${seconds} s atrás` : `posição de ${Math.round(seconds / 60)} min atrás`),
    busGone: 'Este ônibus não está mais no mapa.',
    busesUnavailable: 'Ônibus ao vivo indisponíveis',
  },
  lite: {
    label: 'Visualização 3D',
    enable3d: 'Ativar 3D (árvores e ônibus em 3D)',
    disable3d: 'Desativar 3D (modo leve)',
    autoEnabled: 'Modo leve ativado para o mapa ficar mais fluido.',
    undo: 'Desfazer',
  },
  place: {
    offCampus: 'Local fora do campus',
  },
  access: {
    title: 'Acessibilidade',
    status: {
      yes: 'Acessível',
      partial: 'Parcialmente acessível',
      no: 'Não acessível',
      unknown: 'Sem informação',
    } satisfies Record<AccessStatus, string>,
    unknownHint: 'Ninguém registrou ainda a acessibilidade deste local.',
    source: { osm: 'Fonte: OpenStreetMap', curated: 'Fonte: levantamento do projeto' },
    toggle: 'Acessibilidade',
    legend: 'Legenda de acessibilidade',
    show: 'Mostrar no mapa',
    kinds: {
      ramp: 'Rampa',
      elevator: 'Elevador',
      entrance: 'Entrada',
      toilet: 'Banheiro',
      parking: 'Estacionamento',
      kerb: 'Meio-fio',
      steps: 'Escada',
    } satisfies Record<AccessFeatureKind, string>,
    toilet: 'Banheiro acessível',
    elevator: 'Elevador',
    parking: 'Vagas reservadas',
    level: 'Andar',
    checked: 'Verificado em',
    features: 'Recursos neste prédio',
    yes: 'Sim',
    no: 'Não',
  },
} as const;

/** `2026-10-10` → `10/10/2026`, without going through a time zone. Other formats are shown as written. */
export function formatDate(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  return match ? `${match[3]}/${match[2]}/${match[1]}` : iso;
}

export const buildingKindLabel = (kind: string) => strings.building.kinds[kind] ?? strings.building.kinds.yes!;
