import type { ReportType } from '../domain/reports';
import type { AccessFeatureKind, AccessStatus, PoiCategory } from '../domain/types';

/** Every user-facing string lives here so the UI can be translated later. */
export const strings = {
  appName: 'Mapa USP Butantã',
  close: 'Fechar',
  loading: 'Carregando…',
  dataError: 'Não foi possível carregar os dados do campus.',
  map: {
    ariaLabel: 'Mapa do campus Butantã da USP',
    loading: 'Carregando mapa…',
    error: 'Não foi possível carregar o mapa. Verifique sua conexão.',
  },
  search: {
    placeholder: 'Buscar prédio, instituto ou local',
    label: 'Buscar no campus',
    clear: 'Limpar busca',
    results: 'Resultados da busca',
    noLocalResults: 'Nenhum resultado no campus',
    offCampus: 'Fora do campus',
    institute: 'Unidade',
  },
  sheet: {
    expand: 'Expandir painel',
    collapse: 'Recolher painel',
  },
  indoor: {
    open: 'Ver planta interna',
    close: 'Fechar planta interna',
    levels: 'Andares',
    level: (level: string) => `Nível ${level}`,
    error: 'Não foi possível carregar a planta interna.',
    categories: {
      classroom: 'Sala de aula',
      studio: 'Estúdio',
      laboratory: 'Laboratório',
      library: 'Biblioteca',
      museum: 'Museu',
      auditorium: 'Auditório',
      administration: 'Administração',
      department: 'Departamento',
      food: 'Alimentação',
      services: 'Serviços',
      bathroom: 'Sanitário',
      hall: 'Salão',
      circulation: 'Circulação',
      ramp: 'Rampa',
      stairs: 'Escada',
      elevator: 'Elevador',
      void: 'Vazio',
      technical: 'Área técnica',
    },
  },
  building: {
    unnamed: 'Edifício sem nome',
    kinds: {
      university: 'Prédio universitário',
      dormitory: 'Moradia estudantil',
      roof: 'Cobertura',
      retail: 'Comércio',
      commercial: 'Comércio',
      construction: 'Em construção',
      school: 'Escola',
      greenhouse: 'Estufa',
      hospital: 'Hospital',
      yes: 'Edifício',
    } as Record<string, string>,
  },
  wiki: {
    about: (name: string) => `${name} na Wikipédia`,
    readMore: 'Ler na Wikipédia',
    license: 'Wikipédia, CC BY-SA',
    photos: (title: string) => `Fotos: ${title}`,
    photoAlt: (title: string, position: number) => `${title}, foto ${position}`,
    photoBy: (author: string | undefined) => (author ? `Foto: ${author}` : 'Foto'),
    commons: 'Wikimedia Commons',
    website: 'Site',
  },
  carousel: {
    previous: 'Foto anterior',
    next: 'Próxima foto',
    position: (current: number, total: number) => `${current}/${total}`,
  },
  visualRoutes: {
    title: 'Rotas visuais',
    one: 'Rota visual',
    stepCount: (count: number) => (count === 1 ? '1 passo' : `${count} passos`),
    step: (number: number) => `Passo ${number}`,
    photo: (number: number) => `Foto do passo ${number}`,
    enlarge: (number: number) => `Ampliar a foto do passo ${number}`,
    previousStep: 'Passo anterior',
    nextStep: 'Próximo passo',
    unavailable: 'Não foi possível abrir esta rota visual agora.',
  },
  institute: {
    buildings: 'Prédios',
    noNamedBuildings: 'Nenhum prédio com nome cadastrado.',
  },
  poi: {
    inside: 'Em',
    openingHours: 'Horário',
    categories: {
      food: 'Alimentação',
      library: 'Biblioteca',
      bank: 'Banco',
      atm: 'Caixa eletrônico',
      water: 'Bebedouro',
      toilets: 'Banheiro',
      bike_rental: 'Estação de bicicletas',
      bike_parking: 'Bicicletário',
      parking: 'Estacionamento',
      health: 'Saúde',
      culture: 'Cultura',
      sport: 'Esporte',
      park: 'Área verde',
      shop: 'Loja',
      info: 'Informações',
      other: 'Local',
    } satisfies Record<PoiCategory, string>,
  },
  transit: {
    stop: 'Ponto de ônibus',
    arrivals: 'Próximos ônibus',
    lines: 'Linhas',
    live: 'Previsão ao vivo',
    scheduledNoBuses: 'Horário programado · sem ônibus previstos agora',
    scheduledNoLive: 'Horário programado · dados ao vivo indisponíveis',
    none: 'Sem ônibus previstos agora.',
    noneNoLive: 'Dados ao vivo indisponíveis e sem horários programados para este ponto.',
    unavailable: 'Não foi possível obter as previsões agora.',
    now: 'agora',
    minutes: 'min',
    today: 'hoje',
    tomorrow: 'amanhã',
    accessibleBus: 'acessível',
    bus: 'Ônibus',
    busAccessible: 'Ônibus acessível para cadeira de rodas.',
    busNotAccessible: 'Ônibus sem acessibilidade para cadeira de rodas.',
    busPrefix: 'Prefixo',
    busSeen: (seconds: number) => (seconds < 90 ? `posição de ${seconds} s atrás` : `posição de ${Math.round(seconds / 60)} min atrás`),
    busGone: 'Este ônibus não está mais no mapa.',
    busOffline: 'Sem conexão. A posição do ônibus volta quando a internet voltar.',
    followArrival: (line: string) => `Acompanhar o ônibus ${line} no mapa`,
    allArrivals: 'Todas as chegadas',
    follow: 'Seguir veículo',
    following: 'Posição ao vivo · seguindo',
    followPaused: 'Posição ao vivo · acompanhamento pausado',
    lineStops: 'Pontos da linha',
    stopCount: (count: number) => (count === 1 ? '1 ponto' : `${count} pontos`),
    passed: 'Passou',
    showPassed: (count: number) => (count === 1 ? 'Mostrar 1 ponto anterior' : `Mostrar ${count} pontos anteriores`),
    hidePassed: 'Ocultar pontos anteriores',
    yourStop: 'Seu ponto',
    terminus: 'Ponto final',
    busHere: 'Ônibus aqui',
    estimate: (label: string) => `≈ ${label}`,
    estimatesNote: 'Horários com ≈ são estimativas pela distância; o do seu ponto é a previsão da SPTrans.',
    estimatedNote: 'Horários com ≈ são estimativas pela posição do ônibus no mapa.',
    busesUnavailable: 'Ônibus ao vivo indisponíveis',
  },
  lite: {
    label: 'Visualização 3D',
    hint: 'Árvores e ônibus em 3D. Desative se o mapa ficar lento.',
    autoEnabled: 'Modo leve ativado para o mapa ficar mais fluido.',
    undo: 'Desfazer',
  },
  layers: {
    button: 'Camadas do mapa',
    title: 'Camadas',
    pois: 'Locais no mapa',
    otherPois: 'Outros',
    hiddenInAccessMode: 'Os locais ficam ocultos enquanto a visão de acessibilidade está ativa.',
  },
  offline: {
    banner: 'Sem conexão · ônibus ao vivo indisponíveis',
    arrivals: 'Sem conexão. As previsões voltam quando a internet voltar.',
  },
  update: {
    available: 'Há uma nova versão do mapa.',
    reload: 'Atualizar',
  },
  route: {
    open: 'Traçar rota',
    title: 'Rota',
    toHere: 'Rota até aqui',
    from: 'De',
    to: 'Para',
    swap: 'Inverter origem e destino',
    searchFor: { from: 'Buscar origem', to: 'Buscar destino' },
    endLabel: { from: 'Origem da rota', to: 'Destino da rota' },
    suggestions: 'Sugestões',
    myLocation: 'Minha localização',
    useMyLocation: 'Usar minha localização',
    locationError: 'Não foi possível obter sua localização.',
    mode: 'Tipo de rota',
    modes: { walk: 'A pé', wheelchair: 'Sem degraus', transit: 'Transporte' },
    /** The whole name, where the tab has room for one word only. */
    modeNames: { walk: 'A pé', wheelchair: 'Sem degraus', transit: 'Transporte público' },
    time: {
      button: (choice: string) => `Horário da viagem. ${choice}`,
      title: 'Horário da viagem',
      kinds: { now: 'Sair agora', depart: 'Sair às', arrive: 'Chegar às' },
      when: 'Data e hora',
      chosen: { depart: (when: string) => `Saída: ${when}`, arrive: (when: string) => `Chegada: ${when}` },
      walk: (start: string, end: string) => `Saída ${start} · chegada ${end}`,
    },
    journeys: {
      choose: 'Escolha uma viagem',
      searching: 'Buscando viagens…',
      none: 'Nenhuma viagem de transporte público encontrada para este horário.',
      error: 'Não foi possível buscar viagens agora.',
      direct: 'Direto',
      transfers: (count: number) => (count === 1 ? '1 baldeação' : `${count} baldeações`),
      walk: 'A pé',
      then: 'depois',
      details: 'Detalhes da viagem',
      all: 'Todas as viagens',
      walkLeg: (duration: string, distance: string) => `Caminhe ${duration} (${distance})`,
      transferHere: 'Baldeação neste ponto',
      towards: (headsign: string) => `Sentido ${headsign}`,
      stops: (count: number, duration: string) => `${count === 1 ? '1 parada' : `${count} paradas`} · ${duration}`,
      nonStop: (duration: string) => `Sem paradas · ${duration}`,
      departs: (when: string) => `sai ${when}`,
      vehicles: { bus: 'Ônibus', rail: 'Trem ou metrô' },
      scheduled: 'Horários programados: o veículo pode adiantar ou atrasar.',
      credit: 'Viagens: Transitous · horários das operadoras, dados © OpenStreetMap',
    },
    calculating: 'Calculando rota…',
    error: 'Não foi possível calcular a rota agora.',
    offline: 'Sem conexão. Rotas precisam de internet.',
    stepFree: {
      guaranteed: 'Rota sem degraus.',
      'best-effort': 'Evita escadas quando possível, mas pode conter degraus.',
      no: '',
    },
    hasStairs: 'Atenção: esta rota passa por escadas.',
    detour: (count: number, extra?: string) =>
      `Rota desviando de ${count === 1 ? '1 bloqueio relatado' : `${count} bloqueios relatados`}${extra ? ` (+${extra})` : ''}.`,
    noDetour: 'Há um bloqueio relatado nesta rota e não encontramos um caminho sem degraus que desvie dele.',
    quota: 'O serviço de rotas sem degraus atingiu o limite de uso; esta rota veio de outro serviço.',
    takeStairs: 'Suba ou desça a escada.',
    stairs: 'escada',
    steps: 'Passo a passo',
    providers: { valhalla: 'Rota: Valhalla (FOSSGIS)', ors: 'Rota: openrouteservice' },
    dataCredit: 'dados © OpenStreetMap',
  },
  place: {
    offCampus: 'Local fora do campus',
  },
  review: {
    title: 'Revisão de relatos',
    password: 'Senha de revisão',
    enter: 'Entrar',
    leave: 'Sair',
    wrongPassword: 'Senha incorreta.',
    loadError: 'Não foi possível carregar os relatos.',
    saveError: 'Não foi possível salvar. Tente de novo.',
    pending: 'Pendentes',
    nonePending: 'Nenhum relato aguardando revisão.',
    published: 'Publicados',
    seeOnMap: 'Ver no mapa',
    at: 'às',
    reporterNote: 'Observação de quem relatou (não é pública)',
    publish: 'Publicar',
    confirmPublish: 'Confirmar publicação',
    cancel: 'Cancelar',
    duplicate: 'Duplicado',
    refuse: 'Recusar',
    until: 'Vale até',
    untilHint: 'Sem data, um bloqueio vale 7 dias e um elevador ou banheiro fora de serviço, 14. Os outros ficam no mapa.',
    publicNote: 'Nota pública',
    showsUntil: 'No mapa até',
    showsAlways: 'No mapa sem data para sair.',
    save: 'Salvar',
    withdraw: 'Retirar do mapa',
    changes: 'Mudanças relatadas',
    keep: 'Manter no mapa',
    confirmedOn: 'Confirmado por quem passou em',
  },
  reports: {
    subtitle: 'Relato de quem passou por aqui',
    types: {
      blocked: 'Passagem bloqueada',
      step: 'Degrau ou falta de rampa',
      narrow: 'Calçada estreita',
      elevator: 'Elevador',
      toilet: 'Banheiro acessível',
    } satisfies Record<ReportType, string>,
    /** An elevator or an accessible toilet that does not work, or is not there. */
    states: {
      broken: { elevator: 'Elevador fora de serviço', toilet: 'Banheiro acessível interditado' },
      closed: { elevator: 'Elevador fora de serviço', toilet: 'Banheiro acessível interditado' },
      missing: { elevator: 'Não há elevador', toilet: 'Não há banheiro acessível' },
    },
    passable: { yes: 'Dá para passar', help: 'Só com ajuda', no: 'Não dá para passar' },
    open: 'Relatar um problema',
    action: 'Relatar',
    title: 'Relatar um problema de acessibilidade',
    where: 'Onde está o problema?',
    whereHint: 'Toque no mapa onde está o problema. Um novo toque muda o lugar.',
    mapPoint: 'Ponto no mapa',
    offCampus: 'Esse lugar fica fora do campus.',
    what: 'O que há de errado?',
    examples: {
      blocked: 'Obra, tapume, galho, entulho, veículo na rampa, entrada acessível fechada',
      step: 'Guia sem rebaixamento, degrau na entrada, entrada sem rampa',
      narrow: 'A cadeira de rodas não passa, ou passa apertada',
      elevator: 'Não funciona, ou o prédio não tem',
      toilet: 'Está interditado, ou o prédio não tem',
    } satisfies Record<ReportType, string>,
    passableQuestion: 'Dá para passar de cadeira de rodas?',
    stateQuestion: 'Qual é a situação?',
    answers: {
      yes: 'Sim',
      help: 'Só com ajuda',
      no: 'Não',
      broken: { elevator: 'Não funciona', toilet: 'Interditado' },
      closed: { elevator: 'Não funciona', toilet: 'Interditado' },
      missing: { elevator: 'Não existe', toilet: 'Não existe' },
    },
    addNote: 'Adicionar observação',
    noteLabel: 'Observação (opcional)',
    send: 'Enviar',
    sending: 'Enviando…',
    privacy: 'O relato é anônimo: enviamos o lugar, o tipo e a observação. Ele aparece no mapa depois de revisado.',
    sendResult: {
      sent: 'Relato enviado. Ele aparece no mapa depois de revisado.',
      later: 'Sem conexão. O relato ficou guardado e será enviado quando a internet voltar.',
    },
    sendProblem: {
      refused: 'Não foi possível enviar este relato.',
      'too-many': 'Muitos relatos em pouco tempo. Tente de novo em um minuto.',
    },
    sentLater: 'Relato enviado. Ele aparece no mapa depois de revisado.',
    mine: 'Seu relato',
    pending: 'Aguardando revisão. Por enquanto só aparece neste aparelho.',
    unsent: 'Ainda não enviado: será enviado quando a internet voltar.',
    remove: 'Remover do meu mapa',
    feedback: {
      still: 'Continua assim',
      changed: 'Mudou',
      question: 'O que mudou?',
      kinds: { resolved: 'Foi resolvido', different: 'Está diferente' },
      thanks: 'Obrigado. Sua resposta ajuda a manter o mapa em dia.',
      mayHaveChanged: 'Pode ter mudado',
      confirmed: 'confirmado em',
      problem: {
        'too-many': 'Muitas respostas em pouco tempo. Tente de novo em um minuto.',
        failed: 'Não foi possível enviar agora. Tente de novo.',
      },
    },
    onRoute: {
      title: (count: number) => (count === 1 ? '1 relato nesta rota' : `${count} relatos nesta rota`),
      fromStart: (distance: string) => `a ${distance} do início`,
      atDestination: 'no destino',
    },
    since: 'Relatado em',
    until: 'vale até',
    gone: 'Este relato não está mais no mapa',
    inBuilding: 'Relatos neste prédio',
    layer: 'Avisos temporários',
    layerHint: 'Obras, bloqueios e elevadores fora de serviço relatados por quem passou.',
  },
  access: {
    title: 'Acessibilidade',
    status: {
      yes: 'Acessível',
      partial: 'Parcialmente acessível',
      no: 'Não acessível',
      unknown: 'Sem informação',
    } satisfies Record<AccessStatus, string>,
    unknownHint: 'Ninguém registrou ainda a acessibilidade deste local.',
    source: { osm: 'Fonte: OpenStreetMap', curated: 'Fonte: levantamento do projeto' },
    toggle: 'Acessibilidade',
    legend: 'Legenda de acessibilidade',
    show: 'Mostrar no mapa',
    kinds: {
      ramp: 'Rampa',
      elevator: 'Elevador',
      entrance: 'Entrada',
      toilet: 'Banheiro',
      parking: 'Estacionamento',
      kerb: 'Meio-fio',
      steps: 'Escada',
    } satisfies Record<AccessFeatureKind, string>,
    toilet: 'Banheiro acessível',
    elevator: 'Elevador',
    parking: 'Vagas reservadas',
    level: 'Andar',
    checked: 'Verificado em',
    features: 'Recursos neste prédio',
    yes: 'Sim',
    no: 'Não',
  },
} as const;

/** `2026-10-10` → `10/10/2026`, without going through a time zone. Other formats are shown as written. */
export function formatDate(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  return match ? `${match[3]}/${match[2]}/${match[1]}` : iso;
}

const clock = new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit', timeZone: 'America/Sao_Paulo' });

/** `2026-10-05T12:00:00.000Z` → `09:00`, the time in São Paulo. Empty for anything that is not a moment. */
export function formatTime(iso: string): string {
  const time = Date.parse(iso);
  return Number.isNaN(time) ? '' : clock.format(time);
}

export const buildingKindLabel = (kind: string) => strings.building.kinds[kind] ?? strings.building.kinds.yes!;
